### ISSUE TITLE
SiteUrl (BaseUrl) incorrectly pulled from DB

### ISSUE THREAD

**Issue by peteralewis** [enupal/socializer#10]
enupal/socializer/src/services/Settings.php
getPrimarySiteUrl()

This pulls the baseUrl from the Sites settings directly from the database, this then ignores the setting in the general config and server environment variables. It should be using: 
https://docs.craftcms.com/api/v3/craft-helpers-urlhelper.html#method-basesiteurl

Currently it's pulling the incorrect development URL (stored as a legacy value in the database), because I override the Site URL in config files for each environment.

**Comment by daltonrooney** [comment]
I'm having a similar problem in a headless environment. I need to use the `baseCpUrl` setting for the callback, not the site URL.

**Comment by r0skar** [comment]
@andrelopez I was wondering if there are plans to support this and especially `baseCpUrl` going forward? We are looking for a SSO plugins, but it seems they all have issues. Yours works fine, but we have problems with the siteUrl, because Craft is running in headless mode.

**Comment by daltonrooney** [comment]
Another point of feedback, we're having trouble using Socializer in the context of a multi-site environment, where the callback URL should match the current site and _not_ use the `baseCpUrl`.

**Comment by r0skar** [comment]
> Another point of feedback, we're having trouble using Socializer in the context of a multi-site environment, where the callback URL should match the current site and _not_ use the `baseCpUrl`.

Sounds like this should be a plugin option then(?) And falling back to the current value `siteUrl`, if the option is not set? I think this would cover all usecases and will work seamlessly with active installations.

**Comment by andrelopez** [comment]
I will have an update on this issue soon. Thanks for reporting

**Comment by andrelopez** [comment]
Hi All, we just released Socializer v2.0.2 for Craft4 and Socializer v1.2.1 with a fix to this issue. I have also added a new general setting called `siteUrl` if you need to use Environment Variables. Thank you all
