### ISSUE TITLE
inactive user

### ISSUE THREAD

**Issue by GHF-Hiricis** [enupal/socializer#35]
Hi im having a problem, when i try the google sing up, the user is created but it is inactive by default, im using the free trial so maybe this is because of that, but i did not find anything about this on the website or on the docs. can you tell me if this is a bug or if i just need to upgrade from the free trial?

**Comment by andrelopez** [comment]
Hi @GHF-Hiricis  I was unable to recreate this issue on Craft 3.x.

Could you please confirm what is your Craft CMS version? I found this issue related to Craft CMS 4 -> https://github.com/craftcms/cms/issues/11519

**Comment by GHF-Hiricis** [comment]
yes im using craft 4, my problem is the contrary of the one you found, if i use the registration form it works the user is active and can log in right away, but when i use the google sing up the user is inactive by default and cant log in until i go to my admin account and activate it

**Comment by andrelopez** [comment]
@GHF-Hiricis Could you please confirm your exact Crat CMS version? also could you please let me know what settings you have on the screen below?
Settings -> Users -> Settings

**Comment by GHF-Hiricis** [comment]
sure, the version is Craft Pro 4.2.2 on the user settings i have

Verify email addresses: unchecked
Allow public registration: checked
Validate custom fields on public registration: unchecked
Deactivate users by default: unchecked

and the default user group is the group that i use for my front end user

**Comment by andrelopez** [comment]
@GHF-Hiricis Thanks for following up. We just released Socializer v2.0.1 with a fix to this issue.
