### ISSUE TITLE
Migrating from Google Sign-In to Google Identity Services

### ISSUE THREAD

**Issue by daltonrooney** [enupal/socializer#39]
I just got an email that the Javascript library in use for this plugin will no longer be supported after March 31, 2023. 

> One or more of your web applications uses the legacy Google Sign-In JavaScript library. Please migrate your project(s) to the new Google Identity Services SDK before March 31, 2023.

They included a link to migration guide: https://developers.google.com/identity/gsi/web/guides/migration

**Comment by andrelopez** [comment]
@daltonrooney Thanks for reaching out. Socializer does not use a Javascript library, could you please confirm if this warning is from a different app?

**Comment by daltonrooney** [comment]
@andrelopez Thanks for the follow up. The warning definitely came from the API key associated with the Craft app we're using with Socializer. But I honestly don't remember if we tested other client libraries against that API key. So unless you've heard from other uses of the plugin with the same problem, it's probably safe to close this one.
