### ISSUE TITLE
[Bug]: Unable to edit provider and unable to empty trashed providers

### ISSUE THREAD

**Issue by stigzelm** [enupal/socializer#51]
Craft CMS version: 4.3.7.1
Socializer version: 2.0.2

Once a provider is added. There is no way to edit the provider. The list is missing the link to the edit page (see screenshot).
<img width="1501" alt="Screenshot 2023-02-07 at 18 40 34" src="https://user-images.githubusercontent.com/703669/217308287-924c6142-0dcb-4971-aeac-b919240a80aa.png">

Once a provider is deleted. There is no way to empty the trash from deleted providers (see screenshot).
<img width="1502" alt="Screenshot 2023-02-07 at 18 42 18" src="https://user-images.githubusercontent.com/703669/217308569-2bdbe5e4-9fd3-4fbc-adc7-c21c60be0d0d.png">

**Comment by andrelopez** [comment]
Hi @stigzelm we just released Socializer v2.0.3 with a fix to this issue. Thanks for reporting!
