### ISSUE TITLE
Providers missing ?!

### ISSUE THREAD

**Issue by kinw3b** [enupal/socializer#8]
<img width="1028" alt="Screen Shot 2020-10-15 at 5 46 10 PM" src="https://user-images.githubusercontent.com/9096956/96197135-65fd7400-0f0e-11eb-84a9-e6dfa44ef0fe.png">
Working locally I tested creating new provider for GOOGLE ... Then I removed it and when I went to try to add back again, it is no longer available. Totally Gone! 
---- I tried to unistall the plugin ----- 
<img width="1030" alt="Screen Shot 2020-10-15 at 5 45 53 PM" src="https://user-images.githubusercontent.com/9096956/96197129-639b1a00-0f0e-11eb-8365-af0fb94d873e.png">
But nothing works now. 

Please help asap!

**Comment by andrelopez** [comment]
Hi @kinw3b could you please try to restore from the trash (under the all dropdown)? I'll take a look to the uninstall issue

**Comment by andrelopez** [comment]
Hi @kinw3b please feel free to re-open the ticket if you're still having this issue. Thanks for reporting

**Comment by tamlyn** [comment]
I can confirm that restoring from trash does work. However I find this quite misleading. 

When deleting a provider it shows a popup saying:

> Are you sure you want to delete the selected providers, and all of it's tokens?

![image](https://user-images.githubusercontent.com/115310/112161595-351f1a80-8be3-11eb-97d8-4b6e02e67a37.png)

But when I restore it from trash I see the tokens are still there. This could be a security risk if someone believed the tokens really had been deleted. I also can't see a way to fully delete a provider from the trash. In which case it's not really a trash, more of an archive.
